### ISSUE TITLE
Content information of routes.polystrings-1700 files

### ISSUE THREAD

**Issue by santteegt** [davidbailey/TransportSim#1]
Hello,

I'm wondering if you could give me a quick explanation on how you generated `routes.polystrings-1700` files and what their contents represent. I had a look at the code and I found that you execute `peopleModel.py` and `routeModel.py` to get those files. However, I don't know the content of the files `~/TransportSim/var/tl_2010_06_tabblock10.zip` and `~/TransportSim/var/ca_od_2013/ca_od_main_JT0*`

Regards

**Comment by davidbailey** [comment]
Hi Santiago,

These files are from the United States Census. `tl_2010_06_tabblock10.zip` can be downloaded from here: https://www2.census.gov/geo/tiger/TIGER2010/TABBLOCK/2010/ and the `ca_od_main_JT0` files can be downloaded from here: https://lehd.ces.census.gov/data/lodes/LODES7/ca/od/. The first file is a mapping from census blocks to GIS coordinates and the second file is an origin-destination matrix for California. Please not I used the 2013 version of these files, but you could use any year. (The files are quite large which is why I did not include them in the repository, but I should add a note where to get them from.)

Thanks,
David
